apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
        - name: nginx-container
          image: localhost:30000/nginx-11
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
spec:
  selector:
    app: nginx-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
        - name: nginx-container
          image: localhost:30000/nginx-12
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2
spec:
  selector:
    app: nginx-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-subdomain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-subdomain
  template:
    metadata:
      labels:
        app: nginx-subdomain
    spec:
      containers:
        - name: nginx-container
          image: localhost:30000/nginx-1subdomain
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-subdomain
spec:
  selector:
    app: nginx-subdomain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: nginx-ingress
spec:
  rules:
    - host: duckdns.mathias.dev.br
      http:
        paths:
          - path: /service-1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: nginx-1
                port:
                  number: 80
          - path: /service-2(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: nginx-2
                port:
                  number: 80
    - host: subdomain.duckdns.mathias.dev.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-subdomain
                port:
                  number: 80

# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: nginx-ingress-route
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`kubernetes-server.com`) && PathPrefix(`/service-1`)
#       kind: Rule
#       services:
#         - name: nginx-1
#           port: 80
#       middlewares:
#         - name: stripprefix
#     - match: Host(`kubernetes-server.com`) && PathPrefix(`/service-2`)
#       kind: Rule
#       services:
#         - name: nginx-2
#           port: 80
#       middlewares:
#         - name: stripprefix
#     - match: Host(`subdomain.kubernetes-server.com`)
#       kind: Rule
#       services:
#         - name: nginx-subdomain
#           port: 80
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: stripprefix
# spec:
#   stripPrefix:
#     prefixes:
#       - /service-1
#       - /service-2
