apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1-deployment
spec:
  replicas: 1  # Set the number of replicas as per your requirement
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
        - name: nginx-container
          image: kubernetes-server:31320/nginx:1  # Replace 'nginx:1' with the correct image name
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-service
spec:
  selector:
    app: nginx-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-1-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kubernetes-server.com`) && PathPrefix(`/service-1`)
      kind: Rule
      services:
        - name: nginx-1-service
          port: 80
      middlewares:
        - name: stripprefix
    - match: Host(`kubernetes-server.com`) && PathPrefix(`/service-2`)
      kind: Rule
      services:
        - name: nginx-2-service
          port: 80
      middlewares:
        - name: stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /service-1
      - /service-2
