apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-registry
  template:
    metadata:
      labels:
        app: nginx-test-registry
    spec:
      containers:
        - name: nginx-container
          image: localhost:32000/nginx-test-registry
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-registry
spec:
  selector:
    app: nginx-test-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: nginx-ingress
spec:
  rules:
    - host: duckdns.mathias.dev.br
      http:
        paths:
          - path: /test(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: nginx-test-registry
                port:
                  number: 80