apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-hdd
  namespace: devops-tools
spec:
  storageClassName: external-hdd-hostpath
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 3Gi } }
